name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        mkdir -p dist/lin-amd64 dist/win-amd64
        cd dist/lin-amd64
        GOOS=linux GOARCH=amd64 go build ../../cmd/projectshare-server
        GOOS=linux GOARCH=amd64 go build ../../cmd/projectshare-server-memory
        cd ../../dist/win-amd64
        GOOS=windows GOARCH=amd64 go build ../../cmd/projectshare-server
        GOOS=windows GOARCH=amd64 go build ../../cmd/projectshare-server-memory
        
    - name: Test
      run: go test -v ./...
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: dist
        path: "dist"
